[workspace]
members = [
    "eml-client/src-tauri",
    "eml-client/xtask-frontend",
    "lambda-smtp-relay",
    "notmuch-more",
]
resolver = "2"

[patch.crates-io]
notmuch-more = { path = "notmuch-more" }
